name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run CI checks
        env:
          CI: true
        run: |
          yarn prettier --list-different '**/*.{js,json,md,ts,tsx,yml}'
          yarn compile
          yarn lint

      - name: Build app and BFF
        if: github.ref != 'refs/heads/master' || matrix.node-version != '12.x'
        run: yarn build

      - name: Deploy to AWS
        if: github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
        env:
          AWS_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        run: yarn deploy --require-approval never
