name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run CI checks
        run: |
          yarn prettier --list-different '**/*.{js,json,md,ts,tsx,yml}'
          yarn compile
          yarn lint
          yarn build
        env:
          CI: true
